"""Validate deterministic-equivalent R² predictions, including peer review.

The experiment compares theory with paired Monte Carlo for:

  * R²_gen  on natural Gaussian inputs,
  * R²_acc  on each model's own accentuation path,
  * R²_peer on a path generated by an independent ridge fit.

Plot-ready summaries and per-trial arrays are cached under ``tables/``.  Use
``--plot-only`` to restyle the figure without repeating Monte Carlo.
"""
from __future__ import annotations

import argparse
import csv
import logging
import os
import sys
import time
from pathlib import Path

# Login-node home configuration is read-only in some environments.  Keep
# Matplotlib/font caches on local scratch to avoid repeated remote I/O and
# noisy cache warnings.
os.environ.setdefault('MPLCONFIGDIR', '/tmp/accentuationpredrmt-matplotlib')
os.environ.setdefault('XDG_CACHE_HOME', '/tmp/accentuationpredrmt-xdg-cache')

import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from rmt_core import (  # noqa: E402
    SpectrumKappa,
    accentuation_error_theory,
    accentuation_r2_theory,
    generalization_r2_theory,
    isotropic_spectrum,
    peer_review_error_theory,
    peer_review_r2_theory,
    peer_review_theory,
    powerlaw_spectrum,
    run_paired_monte_carlo,
)


SUMMARY_PATH = REPO_ROOT / 'tables' / 'r2_peer_validation_summary.csv'
CASE_DIR = REPO_ROOT / 'tables' / 'r2_peer_validation_cases'
FIGURE_PATH = REPO_ROOT / 'figures' / 'peer_validation' / 'r2_peer_validation.png'
ERROR_FIGURE_PATH = (
    REPO_ROOT / 'figures' / 'peer_validation' / 'error_peer_validation.png')
DEFAULT_LOG_PATH = REPO_ROOT / 'logs' / 'r2_peer_validation.log'


def configure_logging(path: Path) -> logging.Logger:
    path.parent.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger('r2_peer_validation')
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    formatter = logging.Formatter('%(asctime)s | %(message)s', '%Y-%m-%d %H:%M:%S')
    stream = logging.StreamHandler(sys.stdout)
    stream.setFormatter(formatter)
    file_handler = logging.FileHandler(path, mode='a')
    file_handler.setFormatter(formatter)
    logger.addHandler(stream)
    logger.addHandler(file_handler)
    return logger


def spectrum_from_name(name: str, d: int) -> tuple[np.ndarray, np.ndarray]:
    if name == 'isotropic':
        return isotropic_spectrum(d)
    if name == 'powerlaw_1':
        return powerlaw_spectrum(d, alpha=1.0)
    if name == 'powerlaw_1p5':
        return powerlaw_spectrum(d, alpha=1.5)
    raise ValueError(f'Unknown spectrum {name!r}')


def float_tag(value: float) -> str:
    return f'{value:g}'.replace('.', 'p').replace('-', 'm')


def case_path(spectrum: str, d: int, n: int, lam: float, sigma: float,
              n_trials: int, seed: int) -> Path:
    tag = (
        f'{spectrum}_d{d}_n{n}_lam{float_tag(lam)}_sigma{float_tag(sigma)}'
        f'_trials{n_trials}_seed{seed}.npz'
    )
    return CASE_DIR / tag


def make_beta_star(eigenvalues: np.ndarray, seed: int) -> np.ndarray:
    """Draw a fixed teacher and normalize its natural signal variance to one."""
    rng = np.random.default_rng(seed)
    beta_star = rng.standard_normal(len(eigenvalues))
    signal_power = float(np.sum(eigenvalues * beta_star ** 2))
    return beta_star / np.sqrt(signal_power)


def theory_row(eigenvalues: np.ndarray, beta_star: np.ndarray, n: int,
               lam: float, sigma: float) -> dict[str, float]:
    gamma = len(eigenvalues) / n
    kappa = SpectrumKappa(eigenvalues, gamma)(lam)
    r2_gen, gen_error, signal_power = generalization_r2_theory(
        eigenvalues, beta_star, kappa, sigma, n)
    acc_error, alignment, _ = accentuation_error_theory(
        eigenvalues, beta_star, kappa, sigma, n)
    acc_error_var, _, _ = accentuation_error_theory(
        eigenvalues, beta_star, kappa, sigma, n, include_var_R=True)
    r2_acc, _, _ = accentuation_r2_theory(
        eigenvalues, beta_star, kappa, sigma, n)
    r2_acc_delta, _, delta_correction = accentuation_r2_theory(
        eigenvalues, beta_star, kappa, sigma, n,
        include_delta_correction=True)
    peer_error, r2_peer, peer_gain, peer_details = peer_review_theory(
        eigenvalues, beta_star, kappa, sigma, n)
    peer_error_delta, _, peer_error_correction, peer_error_details = (
        peer_review_error_theory(
            eigenvalues, beta_star, kappa, sigma, n,
            include_delta_correction=True))
    r2_peer_delta, peer_gain_delta, peer_delta_correction, peer_delta_details = (
        peer_review_r2_theory(
            eigenvalues, beta_star, kappa, sigma, n,
            include_delta_correction=True))
    return {
        'gamma': gamma,
        'kappa': kappa,
        'signal_power': signal_power,
        'theory_gen_error': gen_error,
        'theory_r2_gen': r2_gen,
        'theory_acc_error': acc_error,
        'theory_acc_error_var': acc_error_var,
        'theory_acc_alignment': alignment,
        'theory_r2_acc': r2_acc,
        'theory_r2_acc_delta': r2_acc_delta,
        'theory_r2_acc_delta_correction': delta_correction,
        'theory_peer_error': peer_error,
        'theory_peer_error_delta': peer_error_delta,
        'theory_peer_error_delta_correction': peer_error_correction,
        'theory_peer_numerator_variance': (
            peer_error_details['peer_numerator_variance']),
        'theory_peer_gain': peer_gain,
        'theory_r2_peer': r2_peer,
        'theory_peer_gain_delta': peer_gain_delta,
        'theory_r2_peer_delta': r2_peer_delta,
        'theory_r2_peer_delta_correction': peer_delta_correction,
        'theory_peer_gain_variance': peer_delta_details['peer_gain_variance'],
        'theory_peer_true_variance': peer_details['peer_true_variance'],
    }


def save_case(path: Path, row: dict[str, object], trials: dict[str, np.ndarray]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {key: np.asarray(value) for key, value in row.items()}
    payload.update({f'trial_{key}': value for key, value in trials.items()})
    np.savez_compressed(path, **payload)


def load_case(path: Path) -> dict[str, object]:
    with np.load(path, allow_pickle=False) as data:
        row = {}
        for key in data.files:
            if key.startswith('trial_'):
                continue
            value = data[key]
            row[key] = value.item() if value.ndim == 0 else value.tolist()
    return row


def write_summary(rows: list[dict[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0])
    with path.open('w', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    path.chmod(0o644)


def read_summary(path: Path) -> list[dict[str, object]]:
    with path.open(newline='') as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        for key, value in list(row.items()):
            if key == 'spectrum':
                continue
            try:
                row[key] = float(value)
            except (TypeError, ValueError):
                pass
    return rows


def plot_summary(rows: list[dict[str, object]], path: Path) -> None:
    spectra = list(dict.fromkeys(str(row['spectrum']) for row in rows))
    metric_specs = [
        ('r2_gen', 'theory_r2_gen', None, r'$R^2_{gen}$'),
        ('r2_acc', 'theory_r2_acc', 'theory_r2_acc_delta', r'$R^2_{acc}$'),
        ('r2_peer', 'theory_r2_peer', 'theory_r2_peer_delta', r'$R^2_{peer}$'),
    ]
    fig, axes = plt.subplots(
        len(spectra), len(metric_specs), figsize=(13, 3.5 * len(spectra)),
        squeeze=False, sharex='col')

    for row_idx, spectrum in enumerate(spectra):
        subset = sorted(
            (row for row in rows if row['spectrum'] == spectrum),
            key=lambda row: float(row['sigma']))
        sigma = np.array([float(row['sigma']) for row in subset])
        for col_idx, (mc_key, theory_key, corrected_key, title) in enumerate(metric_specs):
            ax = axes[row_idx, col_idx]
            mc = np.array([float(row[f'mc_{mc_key}']) for row in subset])
            se = np.array([float(row[f'mc_{mc_key}_se']) for row in subset])
            theory = np.array([float(row[theory_key]) for row in subset])
            ax.errorbar(sigma, mc, yerr=2 * se, fmt='o', capsize=3,
                        color='black', label='MC mean ± 2 SE')
            ax.plot(sigma, theory, '-s', color='C0', label='leading DE')
            if corrected_key is not None:
                corrected = np.array([float(row[corrected_key]) for row in subset])
                ax.plot(sigma, corrected, '--^', color='C3',
                        label='DE + delta correction')
            ax.axhline(1.0, color='0.75', lw=0.8, ls=':')
            ax.axhline(0.0, color='0.85', lw=0.8, ls=':')
            ax.set_title(f'{spectrum}: {title}')
            ax.set_xlabel(r'noise $σ$ (teacher signal variance = 1)')
            ax.set_ylabel(title)
            ax.grid(alpha=0.2)
            if row_idx == 0:
                ax.legend(fontsize=8)

    fig.suptitle(
        'Deterministic-equivalent predictions for natural, own-path, and peer-path R²',
        y=1.01)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=170, bbox_inches='tight')
    path.chmod(0o644)
    plt.close(fig)


def plot_error_summary(rows: list[dict[str, object]], path: Path) -> None:
    """Plot errors from the cached summary without touching trial-level data."""
    spectra = list(dict.fromkeys(str(row['spectrum']) for row in rows))
    metric_specs = [
        ('gen_error', 'theory_gen_error', None, r'$E_{gen}$'),
        ('acc_error', 'theory_acc_error', 'theory_acc_error_var', r'$E_{acc}$'),
        ('peer_error', 'theory_peer_error', 'theory_peer_error_delta', r'$E_{peer}$'),
    ]
    fig, axes = plt.subplots(
        len(spectra), len(metric_specs), figsize=(13, 3.5 * len(spectra)),
        squeeze=False, sharex='col')

    for row_idx, spectrum in enumerate(spectra):
        subset = sorted(
            (row for row in rows if row['spectrum'] == spectrum),
            key=lambda row: float(row['sigma']))
        sigma = np.array([float(row['sigma']) for row in subset])
        for col_idx, (mc_key, theory_key, corrected_key, title) in enumerate(metric_specs):
            ax = axes[row_idx, col_idx]
            mc = np.array([float(row[f'mc_{mc_key}']) for row in subset])
            se = np.array([float(row[f'mc_{mc_key}_se']) for row in subset])
            theory = np.array([float(row[theory_key]) for row in subset])
            ax.errorbar(sigma, mc, yerr=2 * se, fmt='o', capsize=3,
                        color='black', label='MC mean ± 2 SE')
            ax.plot(sigma, theory, '-s', color='C0', label='leading DE')
            if corrected_key is not None:
                corrected = np.array([float(row[corrected_key]) for row in subset])
                ax.plot(sigma, corrected, '--^', color='C3',
                        label='DE + fluctuation correction')
            ax.set_title(f'{spectrum}: {title}')
            ax.set_xlabel(r'noise $σ$ (teacher signal variance = 1)')
            ax.set_ylabel(title)
            ax.grid(alpha=0.2)
            if row_idx == 0:
                ax.legend(fontsize=8)

    fig.suptitle(
        'Natural, own-path, and independent-peer prediction errors', y=1.01)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=170, bbox_inches='tight')
    path.chmod(0o644)
    plt.close(fig)


def benchmark(args: argparse.Namespace, logger: logging.Logger) -> float:
    eigenvalues, eigenvectors = spectrum_from_name(args.spectra[0], args.d)
    beta_star = make_beta_star(eigenvalues, args.seed)
    rng = np.random.default_rng(args.seed + 1)
    result = run_paired_monte_carlo(
        args.n, eigenvalues, eigenvectors, beta_star, args.sigmas[0], args.lam,
        n_trials=args.benchmark_trials, rng=rng, progress=False)
    seconds_per_trial = result['elapsed_seconds'] / args.benchmark_trials
    n_cases = len(args.spectra) * len(args.sigmas)
    projected = seconds_per_trial * args.n_trials * n_cases
    logger.info(
        'Benchmark: %.6f s/trial; projected %.1f s for %d cases × %d trials',
        seconds_per_trial, projected, n_cases, args.n_trials)
    return projected


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument('--d', type=int, default=128)
    parser.add_argument('--n', type=int, default=256)
    parser.add_argument('--lam', type=float, default=0.05)
    parser.add_argument('--sigmas', type=float, nargs='+', default=[0.1, 0.6, 1.0])
    parser.add_argument(
        '--spectra', nargs='+',
        choices=['isotropic', 'powerlaw_1', 'powerlaw_1p5'],
        default=['isotropic', 'powerlaw_1', 'powerlaw_1p5'])
    parser.add_argument('--n-trials', type=int, default=1000)
    parser.add_argument('--benchmark-trials', type=int, default=20)
    parser.add_argument('--seed', type=int, default=20260814)
    parser.add_argument('--force', action='store_true')
    parser.add_argument('--plot-only', action='store_true')
    parser.add_argument('--no-progress', action='store_true')
    parser.add_argument('--log-file', type=Path, default=DEFAULT_LOG_PATH)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    logger = configure_logging(args.log_file)
    if args.plot_only:
        rows = read_summary(SUMMARY_PATH)
        plot_summary(rows, FIGURE_PATH)
        plot_error_summary(rows, ERROR_FIGURE_PATH)
        logger.info('Replotted cached summaries: %s and %s',
                    FIGURE_PATH, ERROR_FIGURE_PATH)
        return

    projected = benchmark(args, logger)
    if projected > 15 * 60:
        logger.warning(
            'Projected runtime exceeds 15 minutes. Profile or move to GPU before scaling.')

    rows: list[dict[str, object]] = []
    total_cases = len(args.spectra) * len(args.sigmas)
    case_index = 0
    full_start = time.perf_counter()
    for spectrum_index, spectrum in enumerate(args.spectra):
        eigenvalues, eigenvectors = spectrum_from_name(spectrum, args.d)
        teacher_seed = args.seed + 1000 * spectrum_index
        beta_star = make_beta_star(eigenvalues, teacher_seed)
        for sigma_index, sigma in enumerate(args.sigmas):
            case_index += 1
            mc_seed = args.seed + 1000 * spectrum_index + 10 * sigma_index + 1
            cache_path = case_path(
                spectrum, args.d, args.n, args.lam, sigma, args.n_trials, mc_seed)
            if cache_path.exists() and not args.force:
                logger.info('[%d/%d] Loading cache %s', case_index, total_cases, cache_path)
                rows.append(load_case(cache_path))
                continue

            logger.info(
                '[%d/%d] Running %s, sigma=%.3g, d=%d, n=%d, trials=%d',
                case_index, total_cases, spectrum, sigma, args.d, args.n,
                args.n_trials)
            row: dict[str, object] = {
                'spectrum': spectrum,
                'd': args.d,
                'n': args.n,
                'lam': args.lam,
                'sigma': sigma,
                'n_trials': args.n_trials,
                'teacher_seed': teacher_seed,
                'mc_seed': mc_seed,
            }
            row.update(theory_row(eigenvalues, beta_star, args.n, args.lam, sigma))
            rng = np.random.default_rng(mc_seed)
            mc = run_paired_monte_carlo(
                args.n, eigenvalues, eigenvectors, beta_star, sigma, args.lam,
                n_trials=args.n_trials, rng=rng,
                progress=not args.no_progress, return_trials=True)
            row['mc_elapsed_seconds'] = mc['elapsed_seconds']
            for key, value in mc.items():
                if key in {'trials', 'elapsed_seconds', 'n_trials'}:
                    continue
                row[f'mc_{key}'] = value
            save_case(cache_path, row, mc['trials'])
            rows.append(row)
            logger.info(
                '[%d/%d] done in %.2fs | R2 gen %.4f/%.4f, acc %.4f/%.4f, peer %.4f/%.4f (theory/MC)',
                case_index, total_cases, mc['elapsed_seconds'],
                row['theory_r2_gen'], row['mc_r2_gen'],
                row['theory_r2_acc'], row['mc_r2_acc'],
                row['theory_r2_peer'], row['mc_r2_peer'])

    rows.sort(key=lambda row: (str(row['spectrum']), float(row['sigma'])))
    write_summary(rows, SUMMARY_PATH)
    plot_summary(rows, FIGURE_PATH)
    plot_error_summary(rows, ERROR_FIGURE_PATH)
    logger.info('Finished in %.2fs', time.perf_counter() - full_start)
    logger.info('Summary cache: %s', SUMMARY_PATH)
    logger.info('Per-case trial caches: %s', CASE_DIR)
    logger.info('Figure: %s', FIGURE_PATH)
    logger.info('Error figure: %s', ERROR_FIGURE_PATH)


if __name__ == '__main__':
    main()
